import type { Character } from "./types";

const _catalog: Character[] = [
  {
    key: "observatorul",
    title: "Observatorul",
    title_en: "The Observer",
    subtitle: "Cel care vede detaliile fine",
    subtitle_en: "The one who sees fine details",
    shortText: "Observatorul poate exprima o atenție fină, orientată spre detalii, semnale și mișcări subtile.",
    shortText_en: "The Observer can express fine attention, oriented toward details, signals, and subtle movements.",
    observedText: "Expresia poate aduce în față o minte care privește înainte de a reacționa — atentă la detalii, la semnale fine și la ceea ce se petrece sub suprafață. Se poate observa o tendință de claritate și discernământ în felul în care chipul se prezintă lumii.",
    observedText_en: "The expression may reveal a mind that observes before reacting — attentive to details, fine signals, and what happens beneath the surface. A tendency toward clarity and discernment can be seen in how the face presents itself to the world.",
    gift: "Darul lui apare în felul în care poate păstra claritatea acolo unde alții trec grăbiți — vede ce scapă, simte ce nu se spune și înțelege înainte de a întreba.",
    gift_en: "Their gift appears in how they can hold clarity where others rush past — they see what slips by, sense what goes unsaid, and understand before asking.",
    shadow: "Când această energie se strânge, observarea poate deveni distanță și viața ajunge să fie privită mai mult decât trăită.",
    shadow_en: "When this energy contracts, observation can become distance and life ends up being watched more than lived.",
    innerNeed: "În profunzime, caută claritate, siguranță interioară și timp suficient pentru a înțelege ce se petrece în jur.",
    innerNeed_en: "At depth, they seek clarity, inner security, and enough time to understand what is happening around them.",
    eqydoPath: "Pentru Observator, practica Eqydo înseamnă întoarcerea de la analiză la senzație. Observarea respirației și a senzațiilor directe îl ajută să rămână prezent fără să transforme totul în gând.",
    eqydoPath_en: "For the Observer, Eqydo practice means returning from analysis to sensation. Observing breath and direct sensations helps them stay present without turning everything into thought.",
    faceSignals: ["frunte mai activă", "privire concentrată", "ochi atenți", "expresie reținută", "simetrie relativ bună"],
    recommendedPractices: ["Respirație în aria nazală", "Observarea senzațiilor", "Privire blândă"],
    introspectionQuestion: "Ce observi atât de mult încât uiți să trăiești?",
    introspectionQuestion_en: "What do you observe so much that you forget to live?",
    transformationDirection: "Drumul se deschide când analiza lasă loc senzației directe.",
    transformationDirection_en: "The path opens when analysis gives way to direct sensation.",
  },
  {
    key: "conducatorul",
    title: "Conducătorul",
    title_en: "The Leader",
    subtitle: "Cel care ține direcția",
    subtitle_en: "The one who holds the direction",
    shortText: "Conducătorul poate exprima direcție, voință și capacitatea de a susține o formă clară în lume.",
    shortText_en: "The Leader can express direction, will, and the capacity to uphold a clear form in the world.",
    observedText: "Expresia poate aduce în față o energie de asumare — o forță care nu ezită să indice direcția și să ducă lucrurile până la capăt. Se poate observa o orientare spre decizie și o prezență care susține fără să ceară validare.",
    observedText_en: "The expression may bring forward an energy of ownership — a force that does not hesitate to indicate direction and see things through. A decision-oriented stance and a presence that sustains without seeking validation can be observed.",
    gift: "Darul lui apare în capacitatea de a ține drumul atunci când ceilalți se îndoiesc — o forță care nu impune, ci susține, și o hotărâre pe care ceilalți o simt ca stabilitate.",
    gift_en: "Their gift appears in the capacity to hold the course when others doubt — a force that doesn't impose but sustains, and a determination others feel as stability.",
    shadow: "Când această energie se strânge, direcția poate deveni control, iar hotărârea — presiune asupra celorlalți și a propriei persoane.",
    shadow_en: "When this energy contracts, direction can become control and determination can become pressure on others and on oneself.",
    innerNeed: "În profunzime, caută ordine, respect și un spațiu în care deciziile lui să fie auzite, nu puse la îndoială.",
    innerNeed_en: "At depth, they seek order, respect, and a space where their decisions are heard, not questioned.",
    eqydoPath: "Practica îl invită să relaxeze controlul și să cultive ascultarea. Forța devine mai profundă atunci când maxilarul se relaxează și respirația conduce înaintea voinței.",
    eqydoPath_en: "Practice invites them to relax control and cultivate listening. Strength deepens when the jaw relaxes and breath leads before will.",
    faceSignals: ["maxilar bine conturat", "bărbie stabilă", "privire directă", "sprâncene ferme", "proporție inferioară puternică"],
    recommendedPractices: ["Relaxarea maxilarului", "Tăcere conștientă", "Ascultare înainte de acțiune"],
    introspectionQuestion: "Unde poți conduce fără să strângi?",
    introspectionQuestion_en: "Where can you lead without gripping?",
    transformationDirection: "Forța sa devine mai profundă când controlul lasă loc conducerii conștiente.",
    transformationDirection_en: "Their strength deepens when control gives way to conscious leadership.",
  },
  {
    key: "protectorul",
    title: "Protectorul",
    title_en: "The Protector",
    subtitle: "Cel care ține spațiul pentru ceilalți",
    subtitle_en: "The one who holds space for others",
    shortText: "Protectorul poate exprima grijă, responsabilitate și o atenție constantă față de nevoile celor din jur.",
    shortText_en: "The Protector can express care, responsibility, and constant attentiveness to the needs of those around them.",
    observedText: "Se poate observa în expresie o prezență care simte ceea ce ceilalți au nevoie înainte de a cere — o grijă discretă care ține spațiul fără să ocupe centrul. Chipul poate sugera o stabilitate dobândită prin responsabilitate asumată.",
    observedText_en: "The expression may show a presence that senses what others need before they ask — a quiet care that holds space without occupying the center. The face may suggest a stability earned through responsibility embraced.",
    gift: "Darul lui apare în felul în care creează siguranță fără să ceară nimic în schimb — o loialitate discretă și o stabilitate pe care ceilalți o simt fără să o explice.",
    gift_en: "Their gift appears in how they create safety without asking anything in return — a quiet loyalty and a stability others feel without being able to explain it.",
    shadow: "Când această energie se strânge, grija pentru ceilalți poate acoperi grija pentru sine și protecția poate deveni povară.",
    shadow_en: "When this energy contracts, care for others can cover care for self and protection can become burden.",
    innerNeed: "În profunzime, caută și el siguranță, apartenența și o recunoaștere simplă a efortului care nu se vede mereu.",
    innerNeed_en: "At depth, they too seek safety, belonging, and simple recognition of the effort that isn't always seen.",
    eqydoPath: "Practica îl invită să întoarcă atenția spre propriul corp înainte de a susține lumea. Respirația în piept și observarea umerilor pot aduce echilibru între grijă și prezența de sine.",
    eqydoPath_en: "Practice invites them to return attention to their own body before sustaining the world. Chest breathing and shoulder awareness can bring balance between care and self-presence.",
    faceSignals: ["obraji plini sau activi", "maxilar stabil", "privire caldă", "gură neutră", "expresie de responsabilitate"],
    recommendedPractices: ["Respirație în piept", "Observarea umerilor", "Limite blânde"],
    introspectionQuestion: "Pe cine protejezi atât de mult încât uiți să te mai simți pe tine?",
    introspectionQuestion_en: "Who do you protect so much that you forget to feel yourself?",
    transformationDirection: "Calea lui se deschide când grija pentru ceilalți include și grija pentru sine.",
    transformationDirection_en: "Their path opens when care for others includes care for self.",
  },
  {
    key: "cautatorul",
    title: "Căutătorul",
    title_en: "The Seeker",
    subtitle: "Cel care merge după sens",
    subtitle_en: "The one who follows meaning",
    shortText: "Căutătorul poate exprima curiozitate, mișcare interioară și o nevoie vie de sens.",
    shortText_en: "The Seeker can express curiosity, inner movement, and a living need for meaning.",
    observedText: "Expresia poate sugera un om aflat în mișcare interioară — cineva căruia întrebarea îi spune mai mult decât răspunsul și pentru care drumul însuși poate fi sensul. Se poate observa o deschidere și o privire mereu orientată puțin mai departe.",
    observedText_en: "The expression may suggest a person in inner motion — someone for whom the question says more than the answer and for whom the journey itself may be the meaning. An openness and a gaze always oriented a little further ahead can be observed.",
    gift: "Darul lui apare în curajul de a ieși din forme vechi și de a ține vie întrebarea. Poate deschide spații pe care alții nu le văd și poate arăta că există mai mult dincolo de ceea ce este deja știut.",
    gift_en: "Their gift appears in the courage to leave old forms behind and keep the question alive. They can open spaces others don't see and show that there is more beyond what is already known.",
    shadow: "Când această energie se strânge, căutarea poate deveni fugă — de prezent, de răspuns, de locul unde drumul cere să te oprești.",
    shadow_en: "When this energy contracts, seeking can become flight — from the present, from the answer, from the place where the path asks you to stop.",
    innerNeed: "În profunzime, caută libertate, sens și suficient spațiu pentru a explora fără să fie grăbit.",
    innerNeed_en: "At depth, they seek freedom, meaning, and enough space to explore without being rushed.",
    eqydoPath: "Practica îl invită spre ancorare. Mersul conștient, simțirea tălpilor și respirația lentă îl ajută să descopere că drumul începe în corp.",
    eqydoPath_en: "Practice invites them toward grounding. Mindful walking, feeling the soles of the feet, and slow breathing help them discover that the journey begins in the body.",
    faceSignals: ["față alungită", "ochi activi", "privire vie", "frunte activă", "expresie mobilă"],
    recommendedPractices: ["Mers conștient", "Ancorare în tălpi", "Respirație lentă"],
    introspectionQuestion: "Ce cauți în afară și poate fi simțit acum în tine?",
    introspectionQuestion_en: "What do you seek outside that might be felt right now within you?",
    transformationDirection: "Drumul se deschide când neliniștea se transformă în direcție conștientă.",
    transformationDirection_en: "The path opens when restlessness transforms into conscious direction.",
  },
  {
    key: "creatorul",
    title: "Creatorul",
    title_en: "The Creator",
    subtitle: "Cel care dă formă trăirii",
    subtitle_en: "The one who gives form to experience",
    shortText: "Creatorul poate exprima sensibilitate, expresie și capacitatea de a transforma o trăire în formă.",
    shortText_en: "The Creator can express sensitivity, expression, and the capacity to transform an experience into form.",
    observedText: "Expresia poate aduce în față o sensibilitate vie — o energie care caută să devină cuvânt, gest, mișcare sau frumusețe. Ca și cum trăirea nu se simte completă până nu capătă o formă care să o facă vizibilă.",
    observedText_en: "The expression may bring forward a living sensitivity — an energy that seeks to become word, gesture, movement, or beauty. As if the experience doesn't feel complete until it takes a form that makes it visible.",
    gift: "Darul lui apare în felul în care transformă o trăire în ceva vizibil — inspirație vie, sensibilitate care creează legătură și capacitatea de a aduce frumusețe acolo unde alții văd obișnuit.",
    gift_en: "Their gift appears in how they transform an experience into something visible — living inspiration, sensitivity that creates connection, and the capacity to bring beauty where others see ordinary.",
    shadow: "Când această energie se strânge, expresia poate căuta confirmare și sensibilitatea poate cere validare continuă. Intensitatea creatoare poate deveni dispersie.",
    shadow_en: "When this energy contracts, expression may seek confirmation and sensitivity can demand continuous validation. Creative intensity can become dispersion.",
    innerNeed: "În profunzime, caută să fie văzut — nu ca imagine, ci ca prezență — și să simtă că ceea ce creează contează.",
    innerNeed_en: "At depth, they seek to be seen — not as image, but as presence — and to feel that what they create matters.",
    eqydoPath: "Practica îl invită spre tăcere creativă. Observarea mâinilor, respirația în abdomen și oprirea impulsului de a demonstra pot transforma inspirația în prezență.",
    eqydoPath_en: "Practice invites them toward creative silence. Observing the hands, abdominal breathing, and pausing the impulse to demonstrate can transform inspiration into presence.",
    faceSignals: ["gură expresivă", "pomeți activi", "asimetrie subtilă", "ochi vii", "expresie mobilă"],
    recommendedPractices: ["Tăcere creativă", "Observarea mâinilor", "Respirație în abdomen"],
    introspectionQuestion: "Ce vrea să se exprime prin tine?",
    introspectionQuestion_en: "What wants to express itself through you?",
    transformationDirection: "Drumul se deschide când expresia nu mai caută confirmare, ci devine prezență.",
    transformationDirection_en: "The path opens when expression no longer seeks confirmation but becomes presence.",
  },
  {
    key: "luptatorul",
    title: "Luptătorul",
    title_en: "The Fighter",
    subtitle: "Cel care trece prin greutate",
    subtitle_en: "The one who moves through difficulty",
    shortText: "Luptătorul poate exprima forță, rezistență și pregătire pentru acțiune.",
    shortText_en: "The Fighter can express strength, resilience, and readiness for action.",
    observedText: "Se poate observa o energie de impact — o forță care se activează natural în fața greutății și care știe să ducă lucrurile până la capăt atunci când alții cedează. Chipul poate sugera o prezență care nu se ferește de dificultate.",
    observedText_en: "An energy of impact can be observed — a force that activates naturally in the face of difficulty and knows how to see things through when others give up. The face may suggest a presence that does not shy away from hardship.",
    gift: "Darul lui apare în momente dificile: curaj care nu calculează, determinare care nu cedează, o rezistență pe care ceilalți se sprijină fără să realizeze.",
    gift_en: "Their gift appears in difficult moments: courage that doesn't calculate, determination that doesn't yield, a resilience others lean on without realizing it.",
    shadow: "Când această energie se strânge, forța poate deveni tensiune și corpul rămâne în gardă chiar și când viața nu mai cere luptă.",
    shadow_en: "When this energy contracts, strength can become tension and the body stays on guard even when life no longer calls for fight.",
    innerNeed: "În profunzime, caută respect, spațiu de acțiune și recunoașterea forței pe care o poartă — care uneori nu este văzută de cei din jur.",
    innerNeed_en: "At depth, they seek respect, space for action, and recognition of the strength they carry — which sometimes goes unseen by those around them.",
    eqydoPath: "Practica îl invită să transforme tensiunea în prezență. Expirația lungă, mișcarea lentă și relaxarea maxilarului îl ajută să păstreze forța fără luptă.",
    eqydoPath_en: "Practice invites them to transform tension into presence. Long exhales, slow movement, and jaw relaxation help them maintain strength without fight.",
    faceSignals: ["maxilar lat", "sprâncene ferme", "bărbie puternică", "privire intensă", "proporție inferioară activă"],
    recommendedPractices: ["Expirație lungă", "Mișcare lentă", "Relaxarea maxilarului"],
    introspectionQuestion: "Ce forță poți păstra fără să lupți?",
    introspectionQuestion_en: "What strength can you hold without fighting?",
    transformationDirection: "Forța sa devine mai profundă când reacția cedează locul prezenței conștiente.",
    transformationDirection_en: "Their strength deepens when reaction gives way to conscious presence.",
  },
  {
    key: "diplomatul",
    title: "Diplomatul",
    title_en: "The Diplomat",
    subtitle: "Cel care creează punți",
    subtitle_en: "The one who builds bridges",
    shortText: "Diplomatul poate exprima tact, adaptare și o atenție naturală la felul în care oamenii se simt în prezența lui.",
    shortText_en: "The Diplomat can express tact, adaptability, and a natural attentiveness to how people feel in their presence.",
    observedText: "Expresia poate sugera o prezență care simte relațiile și reglează tonul fără efort aparent. Se poate observa o atenție la armonie — la felul în care cuvintele cad și la ceea ce poate crea sau rupe o legătură.",
    observedText_en: "The expression may suggest a presence that senses relationships and adjusts tone without apparent effort. Attentiveness to harmony can be observed — to how words land and what can create or break a connection.",
    gift: "Darul lui apare în felul în care poate calma o tensiune sau crea legătură acolo unde aceasta lipsea — tact, eleganță relațională și o adaptare care nu sacrifică autenticitatea.",
    gift_en: "Their gift appears in how they can calm a tension or create connection where it was absent — tact, relational elegance, and adaptability that doesn't sacrifice authenticity.",
    shadow: "Când această energie se strânge, adaptarea poate deveni evitare și propria direcție se pierde în grija de a menține armonia celorlalți.",
    shadow_en: "When this energy contracts, adaptability can become avoidance and one's own direction is lost in the effort to maintain others' harmony.",
    innerNeed: "În profunzime, caută acceptare și relații în care poate fi și el auzit — nu doar ascultătorul care face loc celorlalți.",
    innerNeed_en: "At depth, they seek acceptance and relationships where they too can be heard — not just the listener who makes room for others.",
    eqydoPath: "Practica îl invită să se întoarcă la axul propriu. Simțirea coloanei și rostirea unei intenții clare pot păstra armonia fără să sacrifice propria direcție.",
    eqydoPath_en: "Practice invites them to return to their own axis. Feeling the spine and stating a clear intention can maintain harmony without sacrificing their own direction.",
    faceSignals: ["proporții echilibrate", "gură armonioasă", "privire blândă", "simetrie bună", "expresie socială deschisă"],
    recommendedPractices: ["Simțirea coloanei", "Tăcere înainte de răspuns", "Rostirea unei intenții clare"],
    introspectionQuestion: "Ce alegi tu, dincolo de armonia celorlalți?",
    introspectionQuestion_en: "What do you choose, beyond the harmony of others?",
    transformationDirection: "Calea sa se deschide când adaptarea vine din ax interior, nu din teama de dezacord.",
    transformationDirection_en: "Their path opens when adaptability comes from an inner axis, not from fear of disagreement.",
  },
  {
    key: "interiorizatul",
    title: "Interiorizatul",
    title_en: "The Inward One",
    subtitle: "Cel care trăiește profund înăuntru",
    subtitle_en: "The one who lives deeply within",
    shortText: "Interiorizatul poate exprima profunzime, retragere și o viață interioară bogată.",
    shortText_en: "The Inward One can express depth, withdrawal, and a rich inner life.",
    observedText: "Expresia poate aduce în față o prezență care simte adânc și arată selectiv — o lume interioară amplă, în care trăirile au nevoie de spațiu înainte de a deveni cuvânt.",
    observedText_en: "The expression may bring forward a presence that feels deeply and shows selectively — a wide inner world where experiences need space before becoming words.",
    gift: "Darul lui apare în capacitatea de a sta cu ceea ce este subtil — o intuiție fină, o profunzime care nu se grăbește și o prezență care poate ține liniștea fără să o rupă.",
    gift_en: "Their gift appears in the capacity to sit with what is subtle — a fine intuition, a depth that doesn't rush, and a presence that can hold silence without breaking it.",
    shadow: "Când această energie se strânge, profunzimea poate deveni izolare și trăirile pot rămâne înăuntru mai mult decât e sănătos.",
    shadow_en: "When this energy contracts, depth can become isolation and experiences can stay inside longer than is healthy.",
    innerNeed: "În profunzime, caută siguranță și spațiu interior — o prezență care nu grăbește deschiderea și nu cere să fie explicat ceea ce simte.",
    innerNeed_en: "At depth, they seek safety and inner space — a presence that doesn't rush opening and doesn't ask for what they feel to be explained.",
    eqydoPath: "Practica îl invită spre exprimarea simplă. Scanarea corporală și rostirea unui singur cuvânt simțit pot transforma retragerea în contact autentic.",
    eqydoPath_en: "Practice invites them toward simple expression. Body scanning and stating a single felt word can transform withdrawal into authentic contact.",
    faceSignals: ["privire adâncă", "față alungită sau fină", "gură reținută", "expresie calmă", "ochi concentrați"],
    recommendedPractices: ["Scanare corporală", "Respirație în piept", "Un cuvânt simțit"],
    introspectionQuestion: "Ce parte din tine așteaptă să fie văzută?",
    introspectionQuestion_en: "What part of you is waiting to be seen?",
    transformationDirection: "Calea lui se deschide când lumea interioară bogată găsește o formă de exprimare simplă.",
    transformationDirection_en: "Their path opens when the rich inner world finds a form of simple expression.",
  },
  {
    key: "vizionarul",
    title: "Vizionarul",
    title_en: "The Visionary",
    subtitle: "Cel care vede direcții mari",
    subtitle_en: "The one who sees large directions",
    shortText: "Vizionarul poate exprima orientare spre sens, capacitate de sinteză și o privire care vede dincolo de moment.",
    shortText_en: "The Visionary can express orientation toward meaning, capacity for synthesis, and a gaze that sees beyond the moment.",
    observedText: "Se poate observa o privire orientată dincolo de imediat — o energie care construiește sens, caută conexiuni și simte direcții înainte ca ele să devină vizibile pentru ceilalți.",
    observedText_en: "A gaze oriented beyond the immediate can be observed — an energy that builds meaning, seeks connections, and senses directions before they become visible to others.",
    gift: "Darul lui apare în capacitatea de a vedea întreg când alții văd fragmente — viziune, inspirație și o sinteză care deschide drumuri acolo unde părea că nu există.",
    gift_en: "Their gift appears in the capacity to see the whole when others see fragments — vision, inspiration, and a synthesis that opens paths where none seemed to exist.",
    shadow: "Când această energia se strânge, viziunea poate deveni desprindere de concret și nerăbdare față de pașii mici pe care tot ea îi cere.",
    shadow_en: "When this energy contracts, vision can become detachment from the concrete and impatience with the small steps it itself requires.",
    innerNeed: "În profunzime, caută sens, libertate mentală și un orizont suficient de larg pentru ideile pe care le poartă.",
    innerNeed_en: "At depth, they seek meaning, mental freedom, and a horizon wide enough for the ideas they carry.",
    eqydoPath: "Practica îl invită să coboare viziunea în corp. Simțirea tălpilor, observarea palmelor și alegerea unui singur pas concret susțin viziunea prin prezență.",
    eqydoPath_en: "Practice invites them to bring vision into the body. Feeling the soles, observing the palms, and choosing a single concrete step sustain the vision through presence.",
    faceSignals: ["frunte înaltă", "ochi deschiși", "față alungită", "privire orientată", "expresie luminoasă"],
    recommendedPractices: ["Ancorare în tălpi", "Observarea palmelor", "Alegerea unui pas simplu"],
    introspectionQuestion: "Ce pas concret susține viziunea ta?",
    introspectionQuestion_en: "What concrete step sustains your vision?",
    transformationDirection: "Viziunea sa devine completă când găsește un pas concret în care să se întrupeze.",
    transformationDirection_en: "Their vision becomes complete when it finds a concrete step in which to take form.",
  },
  {
    key: "ingrijitorul",
    title: "Îngrijitorul",
    title_en: "The Caregiver",
    subtitle: "Cel care hrănește viața din jur",
    subtitle_en: "The one who nourishes life around them",
    shortText: "Îngrijitorul poate exprima blândețe, apropiere și disponibilitatea de a susține viața.",
    shortText_en: "The Caregiver can express gentleness, closeness, and willingness to sustain life.",
    observedText: "Expresia poate aduce în față o căldură discretă — o prezență care creează siguranță fără să ocupe spațiu și care știe să susțină fără să condiționeze.",
    observedText_en: "The expression may bring forward a quiet warmth — a presence that creates safety without taking up space and knows how to sustain without conditioning.",
    gift: "Darul lui apare în răbdarea cu care însoțește pe ceilalți — compasiune fără judecată, căldură care creează spațiu sigur și o prezență care poate vindeca prin simplul fapt că este.",
    gift_en: "Their gift appears in the patience with which they accompany others — compassion without judgment, warmth that creates safe space, and a presence that can heal simply by being.",
    shadow: "Când această energie se strânge, grija poate deveni uitare de sine și, treptat, nevoia de a fi necesar pentru ceilalți.",
    shadow_en: "When this energy contracts, care can become self-forgetting and gradually, the need to be needed by others.",
    innerNeed: "În profunzime, caută relații în care dăruirea circulă în ambele sensuri — apropiere adevărată și o recunoaștere care nu trebuie cerută.",
    innerNeed_en: "At depth, they seek relationships where giving flows in both directions — true closeness and recognition that doesn't need to be asked for.",
    eqydoPath: "Practica îl invită să hrănească mai întâi propria prezență. Respirația în abdomen și limitele blânde ajută grija să rămână vie fără epuizare.",
    eqydoPath_en: "Practice invites them to nourish their own presence first. Abdominal breathing and gentle boundaries help care stay alive without exhaustion.",
    faceSignals: ["obraji plini", "expresie caldă", "gură moale", "ochi blânzi", "față rotundă sau echilibrată"],
    recommendedPractices: ["Respirație în abdomen", "Limite blânde", "Observarea inimii"],
    introspectionQuestion: "Cum poți oferi fără să te pierzi?",
    introspectionQuestion_en: "How can you give without losing yourself?",
    transformationDirection: "Dăruirea lui devine durabilă când hrănește mai întâi propria prezență.",
    transformationDirection_en: "Their giving becomes sustainable when they nourish their own presence first.",
  },
  {
    key: "strategul",
    title: "Strategul",
    title_en: "The Strategist",
    subtitle: "Cel care vede pașii înainte",
    subtitle_en: "The one who sees the steps ahead",
    shortText: "Strategul poate exprima claritate practică, anticipare și orientare spre structură.",
    shortText_en: "The Strategist can express practical clarity, anticipation, and orientation toward structure.",
    observedText: "Se poate observa o claritate calculată — o minte atentă la consecințe, care vede pașii următori înainte ca ceilalți să se fi decis pentru primul.",
    observedText_en: "A calculated clarity can be observed — a mind attentive to consequences, that sees the next steps before others have decided on the first.",
    gift: "Darul lui apare în felul în care poate organiza complexul în ceva clar și acționabil — discernământ practic, eficiență și capacitatea de a vedea pașii înainte.",
    gift_en: "Their gift appears in how they can organize the complex into something clear and actionable — practical discernment, efficiency, and the capacity to see steps ahead.",
    shadow: "Când această energie se strânge, strategia poate deveni control subtil și calculul excesiv poate lăsa mai puțin spațiu pentru spontaneitate și relație.",
    shadow_en: "When this energy contracts, strategy can become subtle control and excessive calculation can leave less space for spontaneity and relationship.",
    innerNeed: "În profunzime, caută claritate, un context în care lucrurile se pot organiza și încredere că efortul depus va da rezultate.",
    innerNeed_en: "At depth, they seek clarity, a context where things can be organized, and trust that the effort invested will yield results.",
    eqydoPath: "Practica îl invită să relaxeze impulsul de a controla. Respirația lentă, relaxarea frunții și observarea nevoii de a anticipa pot deschide spațiu pentru spontaneitate.",
    eqydoPath_en: "Practice invites them to relax the impulse to control. Slow breathing, forehead relaxation, and observing the need to anticipate can open space for spontaneity.",
    faceSignals: ["frunte activă", "simetrie bună", "privire analitică", "sprâncene concentrate", "expresie calculată"],
    recommendedPractices: ["Respirație lentă", "Relaxarea frunții", "Observarea impulsului de control"],
    introspectionQuestion: "Ce se întâmplă când lași viața să mute prima piesă?",
    introspectionQuestion_en: "What happens when you let life move the first piece?",
    transformationDirection: "Strategia sa devine vie când calculul lasă loc și neprevăzutului.",
    transformationDirection_en: "Their strategy becomes alive when calculation also makes room for the unexpected.",
  },
  {
    key: "senzitivul",
    title: "Senzitivul",
    title_en: "The Sensitive",
    subtitle: "Cel care simte atmosfera",
    subtitle_en: "The one who feels the atmosphere",
    shortText: "Senzitivul poate exprima receptivitate, percepție fină și sensibilitate la nuanțele din jur.",
    shortText_en: "The Sensitive can express receptivity, fine perception, and sensitivity to the nuances around them.",
    observedText: "Expresia poate aduce în față o receptivitate fină — o sensibilitate care simte atmosfera, emoțiile și schimbările subtile ale mediului înainte ca mintea să le numească.",
    observedText_en: "The expression may bring forward a fine receptivity — a sensitivity that feels the atmosphere, emotions, and subtle environmental shifts before the mind can name them.",
    gift: "Darul lui apare în felul în care poate simți ceea ce este subtil — o empatie vie, o intuiție care lucrează în tăcere și o percepție fină care vede nuanțele invizibile.",
    gift_en: "Their gift appears in how they can feel what is subtle — a living empathy, an intuition that works in silence, and a fine perception that sees invisible nuances.",
    shadow: "Când această energie se strânge, receptivitatea poate deveni absorbție emoțională și granița dintre ce este propriu și ce vine din mediu poate deveni neclară.",
    shadow_en: "When this energy contracts, receptivity can become emotional absorption and the boundary between what is one's own and what comes from the environment can become unclear.",
    innerNeed: "În profunzime, caută delimitare, liniște și un spațiu curat în care sensibilitatea sa să se poată reaseza.",
    innerNeed_en: "At depth, they seek boundaries, quiet, and a clean space where their sensitivity can resettle.",
    eqydoPath: "Practica îl invită spre delimitare corporală. Simțirea pielii, respirația în tălpi și observarea contactului cu solul pot transforma sensibilitatea în claritate.",
    eqydoPath_en: "Practice invites them toward bodily boundary. Feeling the skin, breathing into the soles, and observing contact with the ground can transform sensitivity into clarity.",
    faceSignals: ["ochi larg deschiși", "sprânceană interioară activă", "maxilar fin", "pomeți subtili", "expresie receptivă"],
    recommendedPractices: ["Delimitare corporală", "Simțirea pielii", "Respirație în tălpi"],
    introspectionQuestion: "Ce este al tău și ce doar trece prin tine?",
    introspectionQuestion_en: "What is yours and what merely passes through you?",
    transformationDirection: "Sensibilitatea sa devine resursă când delimitarea îi oferă un ax clar.",
    transformationDirection_en: "Their sensitivity becomes a resource when boundaries give them a clear axis.",
  },
];

export const CHARACTERS: Record<string, Character> = Object.fromEntries(
  _catalog.map((c) => [c.key, c])
);

export const CHARACTER_LIST = _catalog;
export const CHARACTER_KEYS = _catalog.map((c) => c.key);

export function getCharacterByKey(key: string): Character | null {
  return CHARACTERS[key] ?? null;
}
