import type { Direction } from "./types";

const _directions: Direction[] = [
  {
    key: "calm",
    title: "Calm",
    title_en: "Calm",
    shortText: "Ritmul interior se așază. Respirația face loc, și corpul poate încetini.",
    shortText_en: "The inner rhythm settles. Breath makes room, and the body can slow down.",
    recommendedPractice: "Respirație 4-7-8",
    recommendedPractice_en: "4-7-8 Breathing",
    practiceText: "Inspiră pe 4 timpi, reține pe 7, expiră lent pe 8. Repetă de 4 ori, lăsând fiecare expirație să dizolve tensiunea.",
    practiceText_en: "Inhale for 4 counts, hold for 7, exhale slowly for 8. Repeat 4 times, letting each exhale dissolve tension.",
    introspectionQuestion: "Ce anume poate fi lăsat să se așeze chiar acum?",
    introspectionQuestion_en: "What can be allowed to settle right now?",
  },
  {
    key: "claritate",
    title: "Claritate",
    title_en: "Clarity",
    shortText: "Gândul se limpezește când i se face loc. Claritatea apare în tăcere, mai mult decât în efort.",
    shortText_en: "Thought clears when given room. Clarity appears in silence, more than in effort.",
    recommendedPractice: "Observarea gândurilor",
    recommendedPractice_en: "Observing Thoughts",
    practiceText: "Stai nemișcat 5 minute și observă gândurile fără să le urmezi. Lasă-le să treacă ca nori. Notează un singur lucru care rămâne clar.",
    practiceText_en: "Sit still for 5 minutes and observe thoughts without following them. Let them pass like clouds. Note one thing that remains clear.",
    introspectionQuestion: "Ce devine vizibil atunci când taci suficient de mult?",
    introspectionQuestion_en: "What becomes visible when you are quiet long enough?",
  },
  {
    key: "curaj",
    title: "Curaj",
    title_en: "Courage",
    shortText: "Puterea de a face un pas înainte, chiar și cu tremur în voce.",
    shortText_en: "The strength to take a step forward, even with a tremor in the voice.",
    recommendedPractice: "Expirație de eliberare",
    recommendedPractice_en: "Release Exhale",
    practiceText: "Inspiră adânc prin nas, strânge ușor pumnii, apoi expiră puternic prin gură, deschizând palmele. Repetă de 3 ori.",
    practiceText_en: "Inhale deeply through the nose, gently clench your fists, then exhale forcefully through the mouth, opening your palms. Repeat 3 times.",
    introspectionQuestion: "Care este pasul pe care îl amâni și corpul tău îl știe deja?",
    introspectionQuestion_en: "Which step are you postponing, yet your body already knows?",
  },
  {
    key: "expresie",
    title: "Expresie",
    title_en: "Expression",
    shortText: "Trăirea caută formă — un gest, un cuvânt, o mișcare. Expresia se deschide când primește permisiunea.",
    shortText_en: "Experience seeks form — a gesture, a word, a movement. Expression opens when given permission.",
    recommendedPractice: "Mișcare expresivă liberă",
    recommendedPractice_en: "Free Expressive Movement",
    practiceText: "Alege un spațiu privat. Timp de 5 minute, lasă corpul să se miște fără judecată — voce, gesturi, expresii.",
    practiceText_en: "Choose a private space. For 5 minutes, let the body move without judgment — voice, gestures, expressions.",
    introspectionQuestion: "Ce vrea să fie exprimat prin tine și nu a primit încă permisiunea?",
    introspectionQuestion_en: "What wants to be expressed through you and hasn't yet been given permission?",
  },
  {
    key: "incredere",
    title: "Încredere",
    title_en: "Trust",
    shortText: "Sprijinul se simte în corp înainte de a fi găsit în afară — în coloana vertebrală, în tălpi, în răsuflare.",
    shortText_en: "Support is felt in the body before it's found outside — in the spine, in the soles, in the breath.",
    recommendedPractice: "Ancorare în coloana vertebrală",
    recommendedPractice_en: "Spinal Grounding",
    practiceText: "Stai drept, simte contactul cu scaunul sau cu podeaua. Inspiră imaginând că o rădăcină crește din coloana ta spre pământ.",
    practiceText_en: "Sit upright, feel the contact with the chair or floor. Inhale imagining a root growing from your spine into the earth.",
    introspectionQuestion: "Unde în corpul tău există deja o sursă de siguranță?",
    introspectionQuestion_en: "Where in your body is there already a source of security?",
  },
  {
    key: "iubire",
    title: "Iubire",
    title_en: "Love",
    shortText: "Căldura care poate fi îndreptată spre sine înainte de a o oferi altora.",
    shortText_en: "The warmth that can be directed toward oneself before offering it to others.",
    recommendedPractice: "Respirație în zona inimii",
    recommendedPractice_en: "Heart Space Breathing",
    practiceText: "Pune o mână pe piept. Respiră lent, imaginând căldură care se extinde de la inimă spre tot corpul. Spune în gând: Sunt suficient așa cum sunt.",
    practiceText_en: "Place one hand on your chest. Breathe slowly, imagining warmth expanding from the heart through the whole body. Say inwardly: I am enough as I am.",
    introspectionQuestion: "Cum ai vorbi cu tine dacă ai vorbi cu un prieten drag?",
    introspectionQuestion_en: "How would you speak to yourself if you were speaking to a dear friend?",
  },
  {
    key: "disciplina",
    title: "Disciplină",
    title_en: "Discipline",
    shortText: "O structură vie, caldă și repetată cu blândețe — care susține și lasă să crești.",
    shortText_en: "A living, warm structure repeated with gentleness — that sustains and allows growth.",
    recommendedPractice: "Micro-ritual de dimineață",
    recommendedPractice_en: "Morning Micro-Ritual",
    practiceText: "Alege o singură acțiune simplă pe care o vei face mâine dimineață, înainte de orice altceva. Mică și constantă.",
    practiceText_en: "Choose a single simple action you will do tomorrow morning, before anything else. Small and consistent.",
    introspectionQuestion: "Ce disciplină slujește libertatea ta, în loc să o limiteze?",
    introspectionQuestion_en: "What discipline serves your freedom, rather than limiting it?",
  },
  {
    key: "libertate",
    title: "Libertate",
    title_en: "Freedom",
    shortText: "Mișcarea care se dezleagă — în corp, în gând, în pas. Spațiul interior se deschide când îi dai voie.",
    shortText_en: "Movement that untangles — in body, in thought, in step. Inner space opens when given permission.",
    recommendedPractice: "Mers conștient fără destinație",
    recommendedPractice_en: "Aimless Mindful Walking",
    practiceText: "Ieși afară și mergi 10 minute fără destinație sau agendă. Simte tălpile, aerul, lumina. Lasă mintea să se dezlege.",
    practiceText_en: "Go outside and walk for 10 minutes without destination or agenda. Feel the soles, the air, the light. Let the mind untangle.",
    introspectionQuestion: "Ce ar fi dacă ți-ai acorda permisiunea de a nu ști pentru un moment?",
    introspectionQuestion_en: "What if you gave yourself permission to not know, just for a moment?",
  },
  {
    key: "prezenta",
    title: "Prezență",
    title_en: "Presence",
    shortText: "Contactul direct cu ceea ce se petrece acum — în corp, în simțuri, în clipă.",
    shortText_en: "Direct contact with what is happening now — in the body, in the senses, in the moment.",
    recommendedPractice: "Scanare senzorială 5-4-3-2-1",
    recommendedPractice_en: "5-4-3-2-1 Sensory Scan",
    practiceText: "Numește: 5 lucruri pe care le vezi, 4 pe care le simți pe piele, 3 sunete, 2 mirosuri, 1 gust. Fă-o lent, cu atenție deplină.",
    practiceText_en: "Name: 5 things you see, 4 you feel on your skin, 3 sounds, 2 smells, 1 taste. Do it slowly, with full attention.",
    introspectionQuestion: "Ce se schimbă când ești complet aici, fără să adaugi nimic?",
    introspectionQuestion_en: "What changes when you are completely here, adding nothing?",
  },
  {
    key: "echilibru",
    title: "Echilibru",
    title_en: "Balance",
    shortText: "Măsura care integrează — între dăruire și primire, între efort și odihnă.",
    shortText_en: "The measure that integrates — between giving and receiving, between effort and rest.",
    recommendedPractice: "Respirație alternativă",
    recommendedPractice_en: "Alternate Nostril Breathing",
    practiceText: "Închide nara dreaptă, inspiră pe stânga. Închide stânga, deschide dreapta, expiră. Inspiră pe dreapta. Schimbă. Repetă 5 cicluri.",
    practiceText_en: "Close the right nostril, inhale left. Close left, open right, exhale. Inhale right. Switch. Repeat 5 cycles.",
    introspectionQuestion: "Unde simți că dai prea mult sau prea puțin și ce ar aduce echilibru?",
    introspectionQuestion_en: "Where do you sense you're giving too much or too little, and what would bring balance?",
  },
];

export const DIRECTIONS: Record<string, Direction> = Object.fromEntries(
  _directions.map((d) => [d.key, d])
);
export const DIRECTION_LIST = _directions;
export const DIRECTION_KEYS = _directions.map((d) => d.key);

export function getDirectionByKey(key: string): Direction | null {
  return DIRECTIONS[key] ?? null;
}
